/* PRIMEIRO EXERCICIO - LIVRARIA */

/* MODELAGEM CONCEITUAL */

BANCO = LIVRARIA
ENTIDADE = LIVROS

LIVROS

NOME DO LIVRO - CARACTER(100)
NOME DO AUTOR - CARACTER(100)
SEXO DO AUTOR - CARACTER(1)
NUMERO DE PAGINAS - INT(5)
NOME DA EDITORA- CARACTER(30)
VALOR DO LIVRO - FLOAT(10,2)
ESTADO (UF) DA EDITORA - CARACTER(1)	
ANO PUBLICACAO - INT(4)


/* CRIANDO O BD E A ENTIDADE LIVROS */

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO INT (4)
);


/* INSERINDO OS DADOS */

INSERT INTO LIVROS VALUES ('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);